# Site settings
title: Dillon Kearns Agile Software Consulting
email: dillon@dillonkearns.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dillonkearns.com" # the base hostname & protocol for your site
twitter_username: dillontkearns
github_username:  dillonkearns

# Build settings
markdown: kramdown
